language: python

python:
  - 2.7

install:
  - pip install setuptools
  - pip install -r requirements.txt
  - pip install coverage coveralls

script:
  - python setup.py test
  - coverage run --source=cheat_ext -m unittest discover

after_success:
    coveralls
